### ISSUE TITLE
Initial CRAN checklist

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/vegawidget#56]
This will be for our first release to CRAN, which will work with VL 2.6.0 & ES5

- [x] harmonize image API in anticipation of node.js implementation
- [x] update functions to export in `use_vegawidget()`
- [x] test `use_vegawidget()` on an update to `altair`
- [x] merge pull-requests for shiny-interaction
- [x] build pkgdown, clean up articles, function-documentation
- [x] remove deprecated block functions
- [x] update README.md
- [x] create a `cran-release` branch 
- [x] version -> 0.1.0,  make sure version numbers align in NEWS and DESCRIPTION
- [ ] compose a blog post for vegawidget site
- [x] r-hub checks (r-hub seems to be acting strangely)
- [x] update `cran-release` README to reflect cran installation instructions
- [x] update pkgdown badge to "cran-released"
- [x] submit, 🙏

upon acceptance

- [x] merge into `master`
- [x] apply release tag

**Comment by ijlyttle** [comment]
Our next CRAN release will coincide with VL3 being officially released. 

In the interim, we can work with a branch dedicated to VL3.

- [ ] VL3 itself
- [ ] node.js "stuff" @AliciaSchep is working on for images (and validation?)
- [ ] we can remove promise polyfills and other fixes (we will have to require RStudio IDE 1.2)
- [ ] `addDataListener()`
- [ ] start writing using ES6 constructs - at our own pace

**Comment by AliciaSchep** [comment]
One question re CRAN and the 'image' functions... wonder if we should sort out any 'API' differences between the 'webdriver' and 'node' approaches (e.g. a strategy to minimize visible changes down road)?  And maybe try to find a solution for the remote URL for the webdriver approach?  (Or alternatively, depending on the timetable for this release, try to get the 'node' versions into the initial release?)

**Comment by ijlyttle** [comment]
I was thinking that just before I sat down to the computer... you are exactly right! The image API should be (will be) harmonized before going to CRAN.

I have this conceit of wanting to go to CRAN before rstudio::conf, which does not leave a lot of time.

If there is an "easy" fix to the webdriver/remote-URL problem, let's go for it. The node stuff seems like a heavier lift, as I think I might like to swap out *all* of the webdriver stuff when we introduce node. As well, I will want to see if I can ask some RStudio folks about where they see ES6 support going, particularly for Shiny testing.

I guess I am motivated to get this on CRAN now so we can "plant the flag", and to release an ES5 version people can use if they need to. FWIW, going forward, my day-to-day use will be using VL3.

**Comment by ijlyttle** [comment]
Hi @AliciaSchep - on the off chance that you have any time, I think I have this ready to submit to CRAN, Friday morning, all being well. I have the pkgdown site up-to-date.

If you have any last-minute suggestions (or objections), please let me know, or make a PR to master. 

I plan to give everything another look-over in the morning, then to move on with the rest of the checklist.

Thanks!

**Comment by AliciaSchep** [comment]
@ijlyttle I'll take a look now!  I also would like to put in a PR that would address #59 if I don't encounter stumbling blocks.  If that can't be addressed in short time, then perhaps it can be added as a known limitation?

**Comment by AliciaSchep** [comment]
PR at https://github.com/vegawidget/vegawidget/pull/61 for the local data / base_url issue  

Vignettes look great. I hadn't read through the JS one yet, cool stuff!

**Comment by ijlyttle** [comment]
Will have a look presently at #61, thanks!

Thanks also for your kind words, looking forward to crossing the line on this first lap!

**Comment by ijlyttle** [comment]
closing in favor of #65
